export const FETCH_PRODUCT_TYPES = 'settings/FETCH_PRODUCT_TYPES';
export const FETCH_PRODUCT_TYPES_SUCCEEDED = 'settings/FETCH_PRODUCT_TYPES_SUCCEEDED';
export const FETCH_PRODUCT_TYPES_FAILED = 'settings/FETCH_PRODUCT_TYPES_FAILED';
