export const FETCH_PRODUCT_TYPES = 'settings/FETCH_PRODUCT_TYPES';
export const FETCH_PRODUCT_TYPES_SUCCEEDED =
  'settings/FETCH_PRODUCT_TYPES_SUCCEEDED';
export const FETCH_PRODUCT_TYPES_FAILED = 'settings/FETCH_PRODUCT_TYPES_FAILED';

export const UPDATE_PRODUCT_TYPES = 'settings/UPDATE_PRODUCT_TYPES';
export const UPDATE_PRODUCT_TYPES_SUCCEEDED =
  'settings/UPDATE_PRODUCT_TYPES_SUCCEEDED';
export const UPDATE_PRODUCT_TYPES_FAILED =
  'settings/UPDATE_PRODUCT_TYPES_FAILED';
