export const FETCH_SLIPPERS = 'slipper/FETCH_SLIPPERS';
export const FETCH_SLIPPERS_SUCCEEDED = 'slipper/FETCH_SLIPPERS_SUCCEEDED';
export const FETCH_SLIPPERS_FAILED = 'slipper/FETCH_SLIPPERS_FAILED';

export const LOAD_MORE_SLIPPERS = 'slipper/LOAD_MORE_SLIPPERS';
export const LOAD_MORE_SLIPPERS_SUCCEEDED =
  'slipper/LOAD_MORE_SLIPPERS_SUCCEEDED';
export const LOAD_MORE_SLIPPERS_FAILED = 'slipper/LOAD_MORE_SLIPPERS_FAILED';

export const ADD_SLIPPER = 'slipper/ADD_SLIPPER';
export const ADD_SLIPPER_SUCCEEDED = 'slipper/ADD_SLIPPER_SUCCEEDED';
export const ADD_SLIPPER_FAILED = 'slipper/ADD_SLIPPER_FAILED';

export const UPDATE_SLIPPER = 'slipper/UPDATE_SLIPPER';
export const UPDATE_SLIPPER_SUCCEEDED = 'slipper/UPDATE_SLIPPER_SUCCEEDED';
export const UPDATE_SLIPPER_FAILED = 'slipper/UPDATE_SLIPPER_FAILED';

export const DELETE_SLIPPER = 'slipper/DELETE_SLIPPER';
export const DELETE_SLIPPER_SUCCEEDED = 'slipper/DELETE_SLIPPER_SUCCEEDED';
export const DELETE_SLIPPER_FAILED = 'slipper/DELETE_SLIPPER_FAILED';

export const SET_LAST_SLIPPER = 'slipper/SET_LAST_SLIPPER';
