export const FETCH_SHOES = 'shoes/FETCH_SHOES';
export const FETCH_SHOES_SUCCEEDED = 'shoes/FETCH_SHOES_SUCCEEDED';
export const FETCH_SHOES_FAILED = 'shoes/FETCH_SHOES_FAILED';

export const LOAD_MORE_SHOES = 'shoes/LOAD_MORE_SHOES';
export const LOAD_MORE_SHOES_SUCCEEDED = 'shoes/LOAD_MORE_SHOES_SUCCEEDED';
export const LOAD_MORE_SHOES_FAILED = 'shoes/LOAD_MORE_SHOES_FAILED';

export const UPDATE_SHOE = 'shoes/UPDATE_SHOE';
export const UPDATE_SHOE_SUCCEEDED = 'shoes/UPDATE_SHOE_SUCCEEDED';
export const UPDATE_SHOE_FAILED = 'shoes/UPDATE_SHOE_FAILED';

export const DELETE_SHOE = 'shoes/DELETE_SHOE';
export const DELETE_SHOE_SUCCEEDED = 'shoes/DELETE_SHOE_SUCCEEDED';
export const DELETE_SHOE_FAILED = 'shoes/DELETE_SHOE_FAILED';
