export const FETCH_FAVOURITE_SHOES = 'favourite/FETCH_FAVOURITE_SHOES';
export const FETCH_FAVOURITE_SHOES_SUCCEEDED =
  'favourite/FETCH_FAVOURITE_SHOESSUCCEEDED';
export const FETCH_FAVOURITE_SHOES_FAILED =
  'favourite/FETCH_FAVOURITE_SHOESFAILED';
