export const SAVE_PHONE = 'user/SAVE_PHONE';

export const ADD_SUGGESTION = 'user/ADD_SUGGESTION';
export const ADD_SUGGESTION_SUCCEEDED = 'user/ADD_SUGGESTION_SUCCEEDED';
export const ADD_SUGGESTION_FAILED = 'user/ADD_SUGGESTION_FAILED';

export const UPDATE_SUGGESTION = 'user/UPDATE_SUGGESTION';
export const UPDATE_SUGGESTION_SUCCEEDED = 'user/UPDATE_SUGGESTION_SUCCEEDED';
export const UPDATE_SUGGESTION_FAILED = 'user/UPDATE_SUGGESTION_FAILED';
