export const SAVE_PHONE = 'user/SAVE_PHONE';

export const FETCH_SUGGESTION = 'user/FETCH_SUGGESTION';
export const FETCH_SUGGESTION_SUCCEEDED = 'user/FETCH_SUGGESTION_SUCCEEDED';
export const FETCH_SUGGESTION_FAILED = 'user/FETCH_SUGGESTION_FAILED';

export const ADD_SUGGESTION = 'user/ADD_SUGGESTION';
export const ADD_SUGGESTION_SUCCEEDED = 'user/ADD_SUGGESTION_SUCCEEDED';
export const ADD_SUGGESTION_FAILED = 'user/ADD_SUGGESTION_FAILED';

export const UPDATE_SUGGESTION = 'user/UPDATE_SUGGESTION';
export const UPDATE_SUGGESTION_SUCCEEDED = 'user/UPDATE_SUGGESTION_SUCCEEDED';
export const UPDATE_SUGGESTION_FAILED = 'user/UPDATE_SUGGESTION_FAILED';

export const FETCH_USER = 'user/FETCH_USER';
export const FETCH_USER_SUCCEEDED = 'user/FETCH_USER_SUCCEEDED';
export const FETCH_USER_FAILED = 'user/FETCH_USER_FAILED';

export const ADD_NEW_USER = 'user/ADD_NEW_USER';
export const ADD_NEW_USER_SUCCEEDED = 'user/ADD_NEW_USER_SUCCEEDED';
export const ADD_NEW_USER_FAILED = 'user/ADD_NEW_USER_FAILED';

export const UPDATE_USER = 'user/UPDATE_USER';
export const UPDATE_USER_SUCCEEDED = 'user/UPDATE_USER_SUCCEEDED';
export const UPDATE_USER_FAILED = 'user/UPDATE_USER_FAILED';
